# To execute this docker-compose yml file use `docker-compose -f docker-compose-standalone.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-standalone.yml down`
version: "3"
services:
  chrome:
    image: seleniarm/standalone-chromium:latest
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4441:4444"
      - "7900:7900"
    environment:
     - SE_VNC_NO_PASSWORD=1
     - SE_NODE_MAX_SESSIONS=3


  firefox:
    image: seleniarm/standalone-firefox:latest
    hostname: firefox
    privileged: true
    shm_size: 2gb
    ports:
      - "4442:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3
